### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by mapakun** [mapakun/def_html#1]
```


version: '3.8'
services:

    doowarfback:
      build:
        context: ./doowarf_springboot
        dockerfile: Dockerfile
      container_name: doowarfback
      restart: always
      ports:
         - "8080:8080"
    
    doowarfhtml:
      build:
        context: ./doowarf_html
        dockerfile: Dockerfile
      container_name: doowarfhtml
      ports:
        - "80:80"
        - "443:443"
      volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
        
    doowarfdb:
      build:  
        context: ./doowarf_DB
        dockerfile: Dockerfile
      container_name: doowarfdb
      ports:
        - "3307:3306"

    # certbot:
    #   container_name: certbot
    #   image: certbot/certbot
    #   restart: unless-stopped
    #   volumes:
    #   - ./data/certbot/conf:/etc/letsencrypt
    #   - ./data/certbot/www:/var/www/certbot
    #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"



```
